name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
          cache: true

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build for multiple platforms
        run: |
          mkdir -p dist

          # Build for Linux (amd64)
          GOOS=linux GOARCH=amd64 go build -ldflags="-s -w -X main.version=${{ steps.get_version.outputs.VERSION }}" -o dist/awsm-linux-amd64 ./awsm.go

          # Build for Linux (arm64)
          GOOS=linux GOARCH=arm64 go build -ldflags="-s -w -X main.version=${{ steps.get_version.outputs.VERSION }}" -o dist/awsm-linux-arm64 ./awsm.go

          # Build for macOS (amd64)
          GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w -X main.version=${{ steps.get_version.outputs.VERSION }}" -o dist/awsm-darwin-amd64 ./awsm.go

          # Build for macOS (arm64)
          GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w -X main.version=${{ steps.get_version.outputs.VERSION }}" -o dist/awsm-darwin-arm64 ./awsm.go

          # Build for Windows
          GOOS=windows GOARCH=amd64 go build -ldflags="-s -w -X main.version=${{ steps.get_version.outputs.VERSION }}" -o dist/awsm-windows-amd64.exe ./awsm.go

      - name: Create archives
        run: |
          # Create archives for each platform
          cd dist

          # Linux archives
          tar -czf awsm-linux-amd64.tar.gz awsm-linux-amd64
          tar -czf awsm-linux-arm64.tar.gz awsm-linux-arm64

          # macOS archives
          tar -czf awsm-darwin-amd64.tar.gz awsm-darwin-amd64
          tar -czf awsm-darwin-arm64.tar.gz awsm-darwin-arm64

          # Windows archive (zip)
          zip awsm-windows-amd64.zip awsm-windows-amd64.exe

      - name: Create checksums
        run: |
          cd dist
          sha256sum awsm-linux-amd64.tar.gz awsm-linux-arm64.tar.gz awsm-darwin-amd64.tar.gz awsm-darwin-arm64.tar.gz awsm-windows-amd64.zip > checksums.txt

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          files: |
            dist/awsm-linux-amd64.tar.gz
            dist/awsm-linux-arm64.tar.gz
            dist/awsm-darwin-amd64.tar.gz
            dist/awsm-darwin-arm64.tar.gz
            dist/awsm-windows-amd64.zip
            dist/checksums.txt
          generate_release_notes: true
